name: dependency

on: [push]

jobs:
  test1:
    # The installation commands are not platform agnostic and should not work well on Windows or Mac.
    runs-on: ubuntu-latest

    # it needs to build first
    needs: [ build ]

    steps:
      - name: Update apt
        run: sudo apt update
      - name: Install Eigen3
        run: sudo apt install -y libeigen3-dev

